= Mapeamento de sub-rede
:allow-uri-read: 




=== Mapeamento de sub-rede

Com essa versão, você pode gerenciar endereços IP no failover de uma nova maneira usando o mapeamento de sub-rede, que permite adicionar sub-redes para cada vCenter. Ao fazer isso, você define o CIDR IPv4, o gateway padrão e o DNS para cada rede virtual.

Após o failover, a recuperação de desastres do BlueXP  determina o endereço IP apropriado de cada vNIC, observando o CIDR fornecido para a rede virtual mapeada e o usa para derivar o novo endereço IP.

Por exemplo:

* NetworkA: 10,1.1.0/24
* NetworkB: 192.168.1.0/24


O VM1 tem um vNIC (10,1.1,50) que está conetado à NetworkA. O NetworkA é mapeado para o NetworkB nas configurações do plano de replicação.

Após o failover, a recuperação de desastres do BlueXP  substitui a parte de rede do endereço IP original (10,1.1) e mantém o endereço do host (.50) do endereço IP original (10,1.1,50). Para o VM1, a recuperação de desastres do BlueXP  analisa as configurações do CIDR para o NetworkB e usa a parte 192.168.1 da rede NetworkB enquanto mantém a parte do host (.50) para criar o novo endereço IP para o VM1. O novo IP torna-se 192.168.1.50.

Em resumo, o endereço do host permanece o mesmo, enquanto o endereço de rede é substituído pelo que estiver configurado no mapeamento de sub-rede do site. Isso permite que você gerencie a reatribuição de endereços IP após o failover com mais facilidade, especialmente se você tiver centenas de redes e milhares de VMs para gerenciar.

Para obter detalhes sobre como incluir o mapeamento de sub-redes em seus sites, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Adicione sites do vCenter Server"] consulte .



=== Evite a proteção

Agora você pode ignorar a proteção para que o serviço não crie automaticamente uma relação de proteção reversa após um failover do plano de replicação. Isso é útil se você quiser executar operações adicionais no local restaurado antes de colocá-lo novamente on-line na recuperação de desastres do BlueXP .

Quando você inicia um failover, por padrão, o serviço cria automaticamente uma relação de proteção reversa para cada volume no plano de replicação, se o site de origem original estiver on-line. Isso significa que o serviço cria uma relação SnapMirror do site de destino de volta para o site de origem. O serviço também reverte automaticamente a relação do SnapMirror quando você inicia um failback.

Ao iniciar um failover, agora você pode escolher a opção *Skip protection*. Com isso, o serviço não inverte automaticamente a relação do SnapMirror. Em vez disso, ele deixa o volume gravável em ambos os lados do plano de replicação.

Depois que o site de origem original estiver novamente on-line, você poderá estabelecer proteção reversa selecionando *Protect Resources* no menu ações do plano de replicação. Isso tenta criar uma relação de replicação reversa para cada volume no plano. Pode executar este trabalho repetidamente até que a proteçãoão seja restaurada. Quando a proteção é restaurada, você pode iniciar um failback da maneira habitual.

Para obter mais detalhes sobre a proteção contra saltos, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"] consulte .



=== O SnapMirror agenda atualizações no plano de replicação

A recuperação de desastres do BlueXP  agora suporta o uso de soluções de gerenciamento de snapshot externas, como o agendador de políticas nativo do ONTAP SnapMirror ou integrações de terceiros com o ONTAP. Se cada armazenamento de dados (volume) no plano de replicação já tiver uma relação do SnapMirror que está sendo gerenciada em outro lugar, você poderá usar esses snapshots como pontos de recuperação na recuperação de desastres do BlueXP .

Para configurar, na seção Plano de replicação > Mapeamento de recursos, marque a caixa de seleção *usar backups gerenciados de plataforma e programações de retenção* ao configurar o mapeamento de datastores.

Quando a opção é selecionada, a recuperação de desastres do BlueXP  não configura um agendamento de backup. No entanto, você ainda precisa configurar um cronograma de retenção porque snapshots podem ainda ser feitos para operações de teste, failover e failback.

Depois que isso é configurado, o serviço não tira nenhum snapshot agendado regularmente, mas depende da entidade externa para tirar e atualizar esses snapshots.

Para obter detalhes sobre como usar soluções de snapshot externas no plano de replicação, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .
