---
sidebar: sidebar 
permalink: reference/dr-reference-roles.html 
keywords: how bluexp disaster recovery works, what is disaster recovery, bluexp, vmware, vcenter, draas, replicate, failover, failback, fail over, fail back, vmware cloud, netapp intelligent services 
summary: A BlueXP disaster recovery emprega funções para controlar o acesso que cada usuário tem a recursos e ações específicos. 
---
= Acesso baseado em função de BlueXP disaster recovery aos recursos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A BlueXP disaster recovery emprega funções para controlar o acesso que cada usuário tem a recursos e ações específicos.

O serviço usa as seguintes funções específicas para BlueXP disaster recovery.

* *Administrador de recuperação de desastres*: Execute qualquer ação na BlueXP disaster recovery.
* *Administrador de failover de recuperação de desastres*: execute ações de failover e migração na BlueXP disaster recovery.
* *Administrador do aplicativo de recuperação de desastres*: Crie e modifique planos de replicação e inicie failovers de teste.
* *Visualizador de recuperação de desastres*: visualize informações na BlueXP disaster recovery, mas não pode executar nenhuma ação.


Essas funções são específicas para BlueXP disaster recovery e não são as mesmas que as funções de plataforma usadas no BlueXP. Para obter detalhes sobre todas as funções da plataforma BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["A documentação de configuração e administração do BlueXP"^] consulte .

A tabela a seguir indica as ações que cada função de BlueXP disaster recovery pode executar.

[cols="30,20a,20a,20a,20a"]
|===
| Recurso e ação | Administrador de recuperação de desastres | Administrador de failover de recuperação de desastres | Administrador do aplicativo de recuperação de desastres | Visualizador de recuperação de desastres 


| Visualize o painel e todas as guias  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Inicie o teste gratuito  a| 
Sim
 a| 
Não
 a| 
Não
 a| 
Não



| Inicie a descoberta de cargas de trabalho  a| 
Sim
 a| 
Não
 a| 
Não
 a| 
Não



| Ver informações da licença  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Ativar licença  a| 
Sim
 a| 
Não
 a| 
Sim
 a| 
Não



5+| *Na aba Sites*: 


| Ver sites  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Adicionar, modificar ou excluir sites  a| 
Sim
 a| 
Não
 a| 
Não
 a| 
Não



5+| *Na aba Planos de replicação*: 


| Ver planos de replicação  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Ver detalhes do plano de replicação  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Criar ou modificar planos de replicação  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Não



| Crie relatórios  a| 
Sim
 a| 
Não
 a| 
Não
 a| 
Não



| Ver instantâneos  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Executar testes de failover  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Não



| Executar failovers  a| 
Sim
 a| 
Sim
 a| 
Não
 a| 
Não



| Executar failbacks  a| 
Sim
 a| 
Sim
 a| 
Não
 a| 
Não



| Executar migrações  a| 
Sim
 a| 
Sim
 a| 
Não
 a| 
Não



5+| *Na aba Grupos de recursos*: 


| Exibir grupos de recursos  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



| Criar, modificar ou excluir grupos de recursos  a| 
Sim
 a| 
Não
 a| 
Sim
 a| 
Não



5+| *Na aba Monitoramento de Tarefas*: 


| Ver trabalhos  a| 
Sim
 a| 
Não
 a| 
Sim
 a| 
Sim



| Cancelar trabalhos  a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Não

|===