---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introdução à recuperação de desastres do BlueXP usando Amazon EVS e Amazon FSx para NetApp ONTAP. 
---
= Introdução à recuperação de desastres BlueXP usando o Amazon Elastic VMware Service e o Amazon FSx para NetApp ONTAP
:allow-uri-read: 


[role="lead"]
Cada vez mais, os clientes têm se tornado mais dependentes de infraestruturas virtualizadas para cargas de trabalho de computação de produção, como aquelas baseadas no VMware vSphere. À medida que essas máquinas virtuais (VMs) se tornam mais críticas para seus negócios, os clientes precisam protegê-las dos mesmos tipos de desastres que seus recursos computacionais físicos. As soluções de recuperação de desastres (DR) oferecidas atualmente são complexas, caras e exigem muitos recursos. A NetApp, a maior provedora de armazenamento usada para infraestruturas virtualizadas, tem interesse em garantir que as VMs de seus clientes sejam protegidas da mesma forma que protegemos dados hospedados em armazenamento ONTAP de qualquer tipo. Para atingir esse objetivo, a NetApp criou o serviço de recuperação de desastres BlueXP.


NOTE: ESTA DOCUMENTAÇÃO SOBRE OS VEÍCULOS ELÉTRICOS DA AMAZON É FORNECIDA COMO UMA PRÉVIA DA TECNOLOGIA. Com esta oferta de pré-visualização, a NetApp reserva-se o direito de modificar os detalhes, o conteúdo e o cronograma da oferta antes da Disponibilidade Geral.

Um dos principais desafios de qualquer solução de recuperação de desastres (DR) é gerenciar o custo incremental de aquisição, configuração e manutenção de recursos adicionais de computação, rede e armazenamento apenas para fornecer uma infraestrutura de replicação e recuperação de DR. Uma opção popular para proteger recursos virtuais críticos locais é usar recursos virtuais hospedados na nuvem como infraestrutura de replicação e recuperação de DR. A Amazon é um exemplo de solução que pode fornecer recursos econômicos e compatíveis com infraestruturas de VM hospedadas pelo NetApp ONTAP.

A Amazon lançou o Amazon Elastic VMware Service (Amazon EVS), que habilita o VMware Cloud Foundation dentro da sua nuvem privada virtual (VPC). O Amazon EVS oferece a resiliência e o desempenho da AWS, juntamente com o software e as ferramentas VMware familiares, permitindo que os Amazon EVS vCenters sejam integrados como uma extensão da sua infraestrutura virtualizada local.

Embora o Amazon EVS venha com recursos de armazenamento incluídos, o uso de armazenamento nativo pode reduzir sua eficácia para organizações com cargas de trabalho com alto consumo de armazenamento. Nesses casos, a combinação do Amazon EVS com o Amazon FSx para armazenamento NetApp ONTAP (Amazon FSxN) pode proporcionar uma solução de armazenamento mais flexível. Além disso, ao usar soluções de armazenamento NetApp ONTAP localmente para hospedar sua infraestrutura VMware, usar o Amazon EVS com o FSx para ONTAP significa que você obtém os melhores recursos de interoperabilidade e proteção de dados entre suas infraestruturas local e hospedada na nuvem.

Para obter informações sobre o Amazon FSX for NetApp ONTAP, https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introdução ao Amazon FSx para NetApp ONTAP"^] consulte .
