---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Após a instalação do BlueXP Connector, você precisa integrar todos os recursos de armazenamento ONTAP e VMware vCenter que participarão do processo de DR. 
---
= Visão geral da configuração da recuperação de desastres do BlueXP para o Amazon EVS
:allow-uri-read: 


[role="lead"]
Depois de instalar o BlueXP Connector, você precisa integrar todos os recursos de armazenamento ONTAP e VMware vCenter que participarão do processo de recuperação de desastres com a recuperação de desastres do BlueXP.

* link:evs-deploy-guide-config-prereqs.html["Pré-requisitos para Amazon EVS com recuperação de desastres BlueXP"]
* link:evs-deploy-guide-config-add-arrays.html["Adicionar matrizes de armazenamento ONTAP à recuperação de desastres do BlueXP"]
* link:evs-deploy-guide-enable-draas.html["Habilitar recuperação de desastres BlueXP para Amazon EVS"]
* link:evs-deploy-guide-config-add-arrays.html["Adicionar sites do vCenter à recuperação de desastres do BlueXP"]
* link:evs-deploy-guide-add-vcenters.html["Adicionar clusters do vCenter à recuperação de desastres do BlueXP"]

