---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-closing.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introdução à recuperação de desastres do BlueXP usando Amazon EVS e Amazon FSxN. 
---
= Conclusão
:allow-uri-read: 


[role="lead"]
A recuperação de desastres BlueXP oferece uma solução de recuperação de desastres (DR) econômica e em nuvem híbrida para sua infraestrutura VMware local, quando configurada para usar o Amazon EVS e o Amazon FSx para NetApp ONTAP como destino de recuperação de desastres. Isso proporciona um destino de recuperação de desastres robusto para infraestrutura de missão crítica. A recuperação de desastres BlueXP utiliza recursos nativos de proteção de dados ONTAP, respaldados por décadas de experiência em proteção de dados, testada exaustivamente para garantir que seus dados estejam totalmente protegidos.

Para mais informações:

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introdução ao Amazon FSx para NetApp ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Documentação de recuperação de desastres do NetApp BlueXP"]

