---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introdução à recuperação de desastres BlueXP usando Amazon EVS e Amazon FSx para NetApp ONTAP. A recuperação de desastres BlueXP é um produto licenciado que deve ser adquirido antes de poder ser usado. Existem vários tipos de licenças e diversas maneiras de adquiri-las. 
---
= Adicione o serviço de recuperação de desastres BlueXP à sua conta BlueXP para Amazon EVS
:allow-uri-read: 


[role="lead"]
A recuperação de desastres BlueXP é um produto licenciado que deve ser adquirido antes de poder ser utilizado. Existem vários tipos de licenças e diversas maneiras de adquiri-las. Uma licença lhe dá o direito de proteger uma quantidade específica de dados por um período específico.

Para obter mais informações sobre as licenças de recuperação de desastres do BlueXP, consulte link:../get-started/dr-licensing.html["Configurar o licenciamento para recuperação de desastres do BlueXP "] .



== Tipos de licença

Existem dois tipos principais de licença:

* A NetApp oferece uma link:../get-started/dr-licensing.html["Licença de teste de 30 dias"] que você pode usar para avaliar a recuperação de desastres do BlueXP usando seus recursos ONTAP e VMware. Esta licença oferece 30 dias de uso para uma quantidade ilimitada de capacidade protegida.
* Adquira uma licença de produção se desejar proteção contra desastres além do período de teste de 30 dias. Esta licença pode ser adquirida nos marketplaces de qualquer um dos parceiros de nuvem da NetApp, mas, para este guia, recomendamos que você adquira sua licença do *NetApp Intelligent Services* para recuperação de desastres BlueXP usando o Amazon AWS Marketplace. Para saber mais sobre a compra de uma licença pelo Amazon Marketplace, consulte link:../get-started/dr-licensing.html["Inscreva-se no AWS Marketplace"] .




== Dimensione suas necessidades de capacidade de recuperação de desastres

Antes de adquirir sua licença, você deve entender quanta capacidade de armazenamento ONTAP precisa proteger. Uma das vantagens de usar o armazenamento NetApp ONTAP é a alta eficiência com que a NetApp armazena seus dados. Todos os dados armazenados em um volume ONTAP — como um datastore VMware que hospeda VMs — são armazenados de maneira altamente eficiente. O ONTAP adota como padrão três tipos de eficiência de armazenamento ao gravar dados em armazenamento físico: compactação, desduplicação e compactação. O resultado líquido é uma eficiência de armazenamento entre 1,5:1 e 4:1, dependendo dos tipos de dados armazenados. De fato, a NetApp oferece uma  https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["garantia de eficiência de armazenamento"^] para determinadas cargas de trabalho.

Isso pode ser benéfico para você, pois a recuperação de desastres do BlueXP calcula a capacidade para fins de licenciamento após a aplicação de todas as eficiências de armazenamento ONTAP. Por exemplo, digamos que você provisionou um datastore NFS de 100 terabytes (TiB) no vCenter para hospedar 100 VMs que deseja proteger usando o serviço. Além disso, vamos supor que, quando os dados são gravados no volume ONTAP, as técnicas de eficiência de armazenamento aplicadas automaticamente resultem no consumo de apenas 33 TiB por essas VMs (eficiência de armazenamento de 3:1). A recuperação de desastres do BlueXP precisa ser licenciada apenas para 33 TiB, não para 100 TiB. Isso pode representar um benefício muito grande para o custo total de propriedade da sua solução de recuperação de desastres em comparação com outras soluções de recuperação de desastres.

.Passos
. Para determinar a quantidade de dados que está sendo consumida em cada volume que hospeda um armazenamento de dados VMware a ser protegido, determine o consumo de capacidade no disco executando o comando ONTAP CLI para cada volume:  `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` .
+
Por exemplo:

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. Anote o valor do *Total Físico Utilizado* para cada volume. Este é o volume de dados que a recuperação de desastres do BlueXP precisa proteger e é o valor que você usará para determinar quanta capacidade precisa licenciar.

