---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: A revisão dos relatórios de recuperação de desastres pode ajudá-lo a analisar sua preparação para recuperação de desastres. Os relatórios pré-projetados incluem um resumo de failovers e failbacks, detalhes de replicação em todos os locais e detalhes da tarefa do ano passado. 
---
= Criar relatórios de recuperação de desastres
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
A revisão dos relatórios de recuperação de desastres pode ajudá-lo a analisar sua preparação para recuperação de desastres. Os relatórios pré-projetados incluem um resumo de failovers de teste, detalhes do plano de replicação e detalhes da tarefa em todos os sites de uma conta nos últimos sete dias.

Você pode baixar relatórios em formato PDF, HTML ou JSON.

O link Download é válido por seis horas.

.Passos
. No navegador esquerdo do BlueXP , selecione *proteção* > *recuperação de desastres* > *planos de replicação*.
. Na parte superior da página, selecione *criar relatório*.
. Selecione o tipo de formato de arquivo e o período de tempo nos últimos 7 dias.
. Selecione *criar*.
+

NOTE: O relatório pode levar alguns minutos para ser exibido.

. Para fazer o download de um relatório, selecione *Baixar relatório* e selecione-o na pasta Download do administrador.

