---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Para usar a recuperação de desastres do BlueXP , execute algumas etapas para configurá-la. 
---
= Configure sua infraestrutura para recuperação de desastres no BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para usar a recuperação de desastres do BlueXP , execute algumas etapas para configurá-la tanto no Amazon Web Services (AWS) quanto no BlueXP .


TIP: Revise link:../get-started/dr-prerequisites.html["pré-requisitos"] para garantir que seu ambiente esteja pronto.



== Prepare-se para a recuperação de desastres do BlueXP  para proteção no local para no local

Certifique-se de que os requisitos a seguir sejam atendidos antes de configurar a recuperação de desastres do BlueXP  para proteção no local para no local:

* Storage ONTAP
+
** Certifique-se de que tem credenciais ONTAP.
** Crie ou verifique seu local de recuperação de desastres.
** Crie ou verifique o SVM do ONTAP de destino.
** Certifique-se de que os SVMs ONTAP de origem e destino estejam em Contato.


* Clusters do vCenter
+
** Verifique se as VMs que você deseja proteger estão hospedadas em datastores NFS (usando volumes NFS do ONTAP) ou armazenamentos de dados VMFS (usando LUNs iSCSI do NetApp).
** Revisão link:../reference/vcenter-privileges.html["VCenter Privileges"] necessária para o BlueXP  DR.
** Crie uma conta de usuário de recuperação de desastres (não a conta de administrador padrão do vCenter) e atribua o vCenter Privileges à conta.






=== Suporte a proxy inteligente

O conetor BlueXP  suporta proxy inteligente. O proxy inteligente é uma maneira leve, segura e eficiente de conectar seu ambiente local ao serviço BlueXP . Ele fornece uma conexão segura entre o seu ambiente e o serviço BlueXP  sem exigir uma VPN ou acesso direto à Internet. Essa implementação de proxy otimizada descarrega o tráfego da API dentro da rede local.

Quando um proxy é configurado, a recuperação de desastres do BlueXP  tenta se comunicar diretamente com o VMware ou o ONTAP e usa o proxy configurado se a comunicação direta falhar.

A implementação do proxy de recuperação de desastres do BlueXP  requer comunicação da porta 443 entre o conetor e quaisquer vCenter Servers e arrays ONTAP usando um protocolo HTTPS. O agente de recuperação de desastres do BlueXP  no conetor se comunica diretamente com o VMware vSphere, o VC ou o ONTAP ao executar qualquer ação.

Para obter mais informações sobre a configuração geral do proxy no BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configure um conetor para usar um servidor proxy"^] consulte .



== Prepare-se para a recuperação de desastres do BlueXP  para proteção no local para a nuvem usando a AWS

Para configurar a recuperação de desastres do BlueXP  para proteção no local para a nuvem usando a AWS, você precisa configurar o seguinte:

* Configurar o AWS FSX para NetApp ONTAP
* Configure o VMware Cloud no AWS SDDC




=== Configurar o AWS FSX para NetApp ONTAP

* Crie um sistema de arquivos do Amazon FSX for NetApp ONTAP.
+
** Provisione e configure o FSX for ONTAP. O Amazon FSX for NetApp ONTAP é um serviço totalmente gerenciado que fornece armazenamento de arquivos altamente confiável, escalável, de alto desempenho e rico em recursos, desenvolvido no sistema de arquivos NetApp ONTAP.
** Siga as etapas no https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Relatório técnico 4938: Monte o Amazon FSX ONTAP como um armazenamento de dados NFS com o VMware Cloud na AWS"^] e https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Início rápido para o Amazon FSX for NetApp ONTAP"] para provisionar e configurar o FSX for ONTAP.


* Adicione o Amazon FSX for ONTAP ao ambiente de trabalho e adicione credenciais da AWS para o FSX for ONTAP.
* Crie ou verifique seu SVM do ONTAP de destino na instância do AWS FSX for ONTAP.
* Configure a replicação entre o cluster do ONTAP no local de origem e a instância do FSX for ONTAP no BlueXP .


 https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Como configurar um ambiente de trabalho do FSX for ONTAP"^]Consulte para obter os passos detalhados.



=== Configure o VMware Cloud no AWS SDDC

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud na AWS"^] Fornece uma experiência nativa em nuvem para workloads baseados em VMware no ecossistema AWS. Cada data center definido por software (SDDC) da VMware é executado em uma Amazon Virtual Private Cloud (VPC) e fornece uma pilha completa de VMware (incluindo vCenter Server), rede definida por software NSX-T, armazenamento definido por software VSAN e um ou mais hosts ESXi que fornecem recursos de computação e armazenamento para as cargas de trabalho.

Para configurar um ambiente do VMware Cloud na AWS, siga as etapas em https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Implante e configure o ambiente de virtualização na AWS"^]. Um cluster de luz piloto também pode ser usado para fins de recuperação de desastres.
