---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: O BlueXP  Disaster Recovery é um serviço de recuperação de desastres baseado na nuvem que automatiza os workflows de recuperação de desastres. Com a recuperação de desastres do BlueXP  para VMware, é possível replicar workloads da VMware no local que executam o storage ONTAP para um data center definido por software da VMware em nuvens públicas como um local de recuperação de desastres que usa o storage de nuvem da NetApp. 
---
= Novidades na recuperação de desastres do BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba o que há de novo na recuperação de desastres do BlueXP .



== 15 de setembro de 2025

Versão 4.3.5P3



=== Configuração de script para failover de teste

Com esta versão, agora você pode executar scripts em VMs depois que elas forem ligadas durante o processo de failover de teste.  Isso permite que você teste e valide scripts.  Por exemplo, você pode atualizar as montagens NFS para apontar para um novo servidor de destino, garantindo que os aplicativos convidados fiquem totalmente online e que seu processo de recuperação possa ser testado de ponta a ponta.

Para obter mais informações sobre o processo de failover, consultelink:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"] .



=== Processo de failback aprimorado

Durante o failover, o processo de failback agora fica desabilitado até que a descoberta seja concluída.  Isso garante que todas as configurações sejam corretamente identificadas e contabilizadas antes de iniciar um failback, reduzindo o risco de erros.

Para obter mais informações sobre o processo de failback, consultelink:https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failback.html["Fazer failback de aplicativos para a fonte original"] .



== 04 de agosto de 2025

Versão 4.2.5P2



=== Atualizações de BlueXP disaster recovery

Esta versão inclui as seguintes atualizações:

* Melhorou o suporte do VMFS para lidar com o mesmo LUN apresentado por várias máquinas virtuais de armazenamento.
* Melhorou a limpeza de desmontagem do teste para lidar com o armazenamento de dados que já está sendo desmontado e/ou excluído.
* Mapeamento de sub-rede aprimorado para que agora valide se o gateway inserido está contido na rede fornecida.
* Foi corrigido um problema que poderia causar falha no plano de replicação se o nome da VM contivesse ".com".
* Foi removida uma restrição que impedia que o volume de destino fosse o mesmo que o volume de origem ao criar o volume como parte da criação do plano de replicação.
* Adicionou suporte para uma assinatura de pagamento conforme o uso (PAYGO) para o NetApp Intelligent Services no Azure Marketplace e adicionou um link para o Azure Marketplace na caixa de diálogo de teste gratuito.
+
Para mais detalhes, veja https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["Licenciamento de BlueXP disaster recovery"] e https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurar o licenciamento para recuperação de desastres do BlueXP "] .





== 14 de julho de 2025

Versão 4.2.5



=== Funções do usuário na BlueXP disaster recovery

A BlueXP disaster recovery agora emprega funções para controlar o acesso que cada usuário tem a recursos e ações específicos.

O serviço usa as seguintes funções específicas para BlueXP disaster recovery.

* *Administrador de recuperação de desastres*: Execute qualquer ação na BlueXP disaster recovery.
* *Administrador de failover de recuperação de desastres*: execute ações de failover e migração na BlueXP disaster recovery.
* *Administrador do aplicativo de recuperação de desastres*: Crie e modifique planos de replicação e inicie failovers de teste.
* *Visualizador de recuperação de desastres*: visualize informações na BlueXP disaster recovery, mas não pode executar nenhuma ação.


Se estiver clicando no serviço de BlueXP disaster recovery e configurando-o pela primeira vez, você deverá ter a permissão *SnapCenterAdmin* ou ter a função *Administrador da organização*.

Para obter detalhes,  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Funções e permissões de usuário na BlueXP disaster recovery"]consulte .

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do BlueXP para todos os serviços"^].



=== Outras atualizações na BlueXP disaster recovery

* Descoberta de rede aprimorada
* Melhorias de escalabilidade:
+
** Filtragem dos metadados necessários em vez de todos os detalhes
** Melhorias na descoberta para recuperar e atualizar recursos de VM mais rapidamente
** Otimização de memória e otimização de desempenho para recuperação e atualização de dados
** Melhorias na criação de clientes do vCenter SDK e no gerenciamento de pools


* Gerenciamento de dados obsoletos na próxima descoberta agendada ou manual:
+
** Quando uma VM é excluída no vCenter, a BlueXP disaster recovery agora a remove automaticamente do plano de replicação.
** Quando um armazenamento de dados ou rede é excluído no vCenter, a BlueXP disaster recovery agora o exclui do plano de replicação e do grupo de recursos.
** Quando um cluster, host ou datacenter é excluído no vCenter, a BlueXP disaster recovery agora o exclui do plano de replicação e do grupo de recursos.


* Agora você pode acessar a documentação do Swagger no modo anônimo do seu navegador. Você pode acessá-la na BlueXP disaster recovery, na opção Configurações > Documentação da API ou diretamente no seguinte URL no modo anônimo do seu navegador:  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentação do Swagger"^] .
* Em algumas situações, após uma operação de failback, o iGroup era deixado para trás após a conclusão da operação. Esta atualização remove o iGroup se ele estiver obsoleto.
* Se o FQDN do NFS foi usado no plano de replicação, a BlueXP disaster recovery agora o resolve para um endereço IP. Esta atualização é útil se o FQDN não puder ser resolvido no site de recuperação de desastres.
* Melhorias no alinhamento da interface do usuário
* Melhorias de log para capturar os detalhes de dimensionamento do vCenter após a descoberta bem-sucedida




== 30 de junho de 2025

Versão 4.2.4P2



=== Melhorias na descoberta

Esta atualização melhora o processo de descoberta, o que reduz o tempo necessário para a descoberta.



== 23 de junho de 2025

Versão 4.2.4P1



=== Melhorias no mapeamento de sub-redes

Esta atualização aprimora a caixa de diálogo Adicionar e Editar Mapeamento de Sub-redes com uma nova funcionalidade de pesquisa. Agora você pode encontrar sub-redes específicas rapidamente inserindo termos de pesquisa, facilitando o gerenciamento de mapeamentos de sub-redes.



== 9 de junho de 2025

Versão 4.2.4



=== Suporte à solução de senha do administrador local do Windows (LAPS)

O Windows Local Administrator Password Solution (Windows LAPS) é um recurso do Windows que gerencia e faz backup automaticamente da senha de uma conta de administrador local no Active Directory.

Agora você pode selecionar opções de mapeamento de sub-rede e marcar a opção LAPS fornecendo os detalhes do controlador de domínio. Com esta opção, você não precisa fornecer uma senha para cada uma das suas máquinas virtuais.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



== 13 de maio de 2025

Versão 4.2.3



=== Mapeamento de sub-rede

Com essa versão, você pode gerenciar endereços IP no failover de uma nova maneira usando o mapeamento de sub-rede, que permite adicionar sub-redes para cada vCenter. Ao fazer isso, você define o CIDR IPv4, o gateway padrão e o DNS para cada rede virtual.

Após o failover, a recuperação de desastres do BlueXP  determina o endereço IP apropriado de cada vNIC, observando o CIDR fornecido para a rede virtual mapeada e o usa para derivar o novo endereço IP.

Por exemplo:

* NetworkA: 10,1.1.0/24
* NetworkB: 192.168.1.0/24


O VM1 tem um vNIC (10,1.1,50) que está conetado à NetworkA. O NetworkA é mapeado para o NetworkB nas configurações do plano de replicação.

Após o failover, a recuperação de desastres do BlueXP  substitui a parte de rede do endereço IP original (10,1.1) e mantém o endereço do host (.50) do endereço IP original (10,1.1,50). Para o VM1, a recuperação de desastres do BlueXP  analisa as configurações do CIDR para o NetworkB e usa a parte 192.168.1 da rede NetworkB enquanto mantém a parte do host (.50) para criar o novo endereço IP para o VM1. O novo IP torna-se 192.168.1.50.

Em resumo, o endereço do host permanece o mesmo, enquanto o endereço de rede é substituído pelo que estiver configurado no mapeamento de sub-rede do site. Isso permite que você gerencie a reatribuição de endereços IP após o failover com mais facilidade, especialmente se você tiver centenas de redes e milhares de VMs para gerenciar.

Para obter detalhes sobre como incluir o mapeamento de sub-redes em seus sites, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Adicione sites do vCenter Server"] consulte .



=== Evite a proteção

Agora você pode ignorar a proteção para que o serviço não crie automaticamente uma relação de proteção reversa após um failover do plano de replicação. Isso é útil se você quiser executar operações adicionais no local restaurado antes de colocá-lo novamente on-line na recuperação de desastres do BlueXP .

Quando você inicia um failover, por padrão, o serviço cria automaticamente uma relação de proteção reversa para cada volume no plano de replicação, se o site de origem original estiver on-line. Isso significa que o serviço cria uma relação SnapMirror do site de destino de volta para o site de origem. O serviço também reverte automaticamente a relação do SnapMirror quando você inicia um failback.

Ao iniciar um failover, agora você pode escolher a opção *Skip protection*. Com isso, o serviço não inverte automaticamente a relação do SnapMirror. Em vez disso, ele deixa o volume gravável em ambos os lados do plano de replicação.

Depois que o site de origem original estiver novamente on-line, você poderá estabelecer proteção reversa selecionando *Protect Resources* no menu ações do plano de replicação. Isso tenta criar uma relação de replicação reversa para cada volume no plano. Pode executar este trabalho repetidamente até que a proteçãoão seja restaurada. Quando a proteção é restaurada, você pode iniciar um failback da maneira habitual.

Para obter mais detalhes sobre a proteção contra saltos, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"] consulte .



=== O SnapMirror agenda atualizações no plano de replicação

A recuperação de desastres do BlueXP  agora suporta o uso de soluções de gerenciamento de snapshot externas, como o agendador de políticas nativo do ONTAP SnapMirror ou integrações de terceiros com o ONTAP. Se cada armazenamento de dados (volume) no plano de replicação já tiver uma relação do SnapMirror que está sendo gerenciada em outro lugar, você poderá usar esses snapshots como pontos de recuperação na recuperação de desastres do BlueXP .

Para configurar, na seção Plano de replicação > Mapeamento de recursos, marque a caixa de seleção *usar backups gerenciados de plataforma e programações de retenção* ao configurar o mapeamento de datastores.

Quando a opção é selecionada, a recuperação de desastres do BlueXP  não configura um agendamento de backup. No entanto, você ainda precisa configurar um cronograma de retenção porque snapshots podem ainda ser feitos para operações de teste, failover e failback.

Depois que isso é configurado, o serviço não tira nenhum snapshot agendado regularmente, mas depende da entidade externa para tirar e atualizar esses snapshots.

Para obter detalhes sobre como usar soluções de snapshot externas no plano de replicação, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



== 16 de abril de 2025

Versão 4.2.2



=== Detecção programada para VMs

A recuperação de desastres do BlueXP  realiza a descoberta a cada 24 horas. Com esta versão, agora você pode personalizar o cronograma de descoberta para atender às suas necessidades e reduzir o impactos no desempenho quando necessário. Por exemplo, se você tiver um grande número de VMs, poderá definir a programação de descoberta para ser executada a cada 48 horas. Se você tiver um pequeno número de VMs, poderá definir o agendamento de descoberta para ser executado a cada 12 horas.

Se você não deseja agendar a descoberta, você pode desativar a opção de descoberta agendada e atualizar a descoberta manualmente a qualquer momento.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Adicione sites do vCenter Server"] consulte .



=== Suporte ao datastore do grupo de recursos

Anteriormente, você poderia criar grupos de recursos apenas por VMs. Com essa versão, você pode criar um grupo de recursos por datastores. Quando você estiver criando um plano de replicação e criando um grupo de recursos para esse plano, todas as VMs em um datastore serão listadas. Isso é útil se você tiver um grande número de VMs e quiser agrupá-las por datastore.

Você pode criar um grupo de recursos com um datastore das seguintes maneiras:

* Ao adicionar um grupo de recursos usando datastores, você pode ver uma lista de datastores. Você pode selecionar um ou mais datastores para criar um grupo de recursos.
* Ao criar um plano de replicação e criar um grupo de recursos dentro do plano, você pode ver as VMs nos datastores.


Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Notificações de avaliação gratuita ou expiração de licença

Esta versão fornece notificações de que o teste gratuito expirará em 60 dias para garantir que você tenha tempo para obter uma licença. Esta versão também fornece notificações no dia em que a licença expira.



=== Notificação de atualizações de serviço

Com esta versão, um banner aparece na parte superior para indicar que os serviços estão sendo atualizados e que o serviço é colocado no modo de manutenção. O banner aparece quando o serviço está sendo atualizado e desaparece quando a atualização é concluída. Embora possa continuar a trabalhar na IU enquanto a atualização estiver em curso, não é possível enviar novos trabalhos. Os trabalhos agendados serão executados após a conclusão da atualização e o serviço retornará ao modo de produção.



== 10 de março de 2025

Versão 4.2.1



=== Suporte a proxy inteligente

O conetor BlueXP  suporta proxy inteligente. O proxy inteligente é uma maneira leve, segura e eficiente de conectar seu ambiente local ao serviço BlueXP . Ele fornece uma conexão segura entre o seu ambiente e o serviço BlueXP  sem exigir uma VPN ou acesso direto à Internet. Essa implementação de proxy otimizada descarrega o tráfego da API dentro da rede local.

Quando um proxy é configurado, a recuperação de desastres do BlueXP  tenta se comunicar diretamente com o VMware ou o ONTAP e usa o proxy configurado se a comunicação direta falhar.

A implementação do proxy de recuperação de desastres do BlueXP  requer comunicação da porta 443 entre o conetor e quaisquer vCenter Servers e arrays ONTAP usando um protocolo HTTPS. O agente de recuperação de desastres do BlueXP  no conetor se comunica diretamente com o VMware vSphere, o VC ou o ONTAP ao executar qualquer ação.

Para obter mais informações sobre o proxy inteligente para recuperação de desastres do BlueXP , https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Configure sua infraestrutura para recuperação de desastres no BlueXP "] consulte .

Para obter mais informações sobre a configuração geral do proxy no BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configure um conetor para usar um servidor proxy"^] consulte .



=== Termine o teste gratuito a qualquer momento

Você pode parar o teste gratuito em qualquer dente ou você pode esperar até que ele expire.

 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Termine a avaliação gratuita"]Consulte .



== 19 de fevereiro de 2025

Versão 4,2



=== Suporte ao ASA R2 para VMs e armazenamentos de dados no storage VMFS

Essa versão da recuperação de desastres do BlueXP  oferece suporte ao ASA R2 para VMs e armazenamentos de dados no storage VMFS. Em um sistema ASA R2, o software ONTAP oferece suporte à funcionalidade essencial de SAN e remove recursos não suportados em ambientes SAN.

Esta versão suporta os seguintes recursos para o ASA R2:

* Provisionamento de grupo de consistência para armazenamento primário (apenas grupo de consistência plana, ou seja, apenas um nível sem estrutura hierárquica)
* Operações de backup (grupo de consistência), incluindo automação de SnapMirror


O suporte ao ASA R2 na recuperação de desastres do BlueXP  usa o ONTAP 9.16.1.

Embora os datastores possam ser montados em um volume ONTAP ou em uma unidade de armazenamento ASA R2, um grupo de recursos na recuperação de desastres do BlueXP  não pode incluir um datastore do ONTAP e um do ASA R2. Você pode selecionar um datastore do ONTAP ou um datastore do ASA R2 em um grupo de recursos.



== 30 de outubro de 2024



=== Relatórios

Agora você pode gerar e baixar relatórios para ajudá-lo a analisar seu cenário. Os relatórios pré-projetados resumem failovers e failbacks, mostram detalhes de replicação em todos os locais e mostram os detalhes da tarefa nos últimos sete dias.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Criar relatórios de recuperação de desastres"].



=== teste gratuito de 30 dias

Agora você pode se inscrever para uma avaliação gratuita de 30 dias da recuperação de desastres do BlueXP . Anteriormente, as avaliações gratuitas duravam 90 dias.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configure o licenciamento"].



=== Desativar e ativar planos de replicação

Uma versão anterior incluiu atualizações da estrutura de agendamento de teste de failover, que era necessária para dar suporte a programações diárias e semanais. Esta atualização exigiu que você desabilite e reative todos os planos de replicação existentes para que você possa usar as novas programações de teste de failover diárias e semanais. Este é um requisito único.

Veja como:

. No menu superior, selecione *planos de replicação*.
. Selecione um plano e selecione o ícone ações para exibir o menu suspenso.
. Selecione *Desativar*.
. Após alguns minutos, selecione *Enable* (Ativar).




=== Mapeamento de pastas

Quando você cria um plano de replicação e mapeia recursos de computação, agora é possível mapear pastas para que as VMs sejam recuperadas em uma pasta especificada para datacenter, cluster e host.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Detalhes da VM disponíveis para failover, failback e failover de teste

Quando uma falha ocorre e você está iniciando um failover, executando um failback ou testando o failover, agora você pode ver detalhes das VMs e identificar quais VMs não reiniciaram.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"].



=== Atraso de inicialização da VM com sequência de inicialização ordenada

Quando você cria um plano de replicação, agora você pode definir um atraso de inicialização para cada VM no plano. Isso permite que você defina uma sequência para que as VMs comecem a garantir que todas as VMs prioritárias One estejam sendo executadas antes que as VMs prioritárias subsequentes sejam iniciadas.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Informações do sistema operacional da VM

Quando você cria um plano de replicação, agora você pode ver o sistema operacional de cada VM no plano. Isso é útil para decidir como agrupar VMs em um grupo de recursos.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Alias de nome da VM

Quando você cria um plano de replicação, agora é possível adicionar um prefixo e sufixo aos nomes da VM no SIT de recuperação de desastres. Isso permite que você use um nome mais descritivo para as VMs no plano.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Limpe os instantâneos antigos

Você pode excluir todos os snapshots que não forem mais necessários além da contagem de retenção especificada. Os snapshots podem se acumular ao longo do tempo quando você diminui a contagem de retenção de snapshots, e agora você pode removê-los para liberar espaço. Você pode fazer isso a qualquer momento sob demanda ou quando você excluir um plano de replicação.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerencie sites, grupos de recursos, planos de replicação, armazenamentos de dados e informações de máquinas virtuais"] consulte .



=== Reconciliar instantâneos

Agora você pode reconciliar snapshots que estão fora de sincronia entre a origem e o destino. Isso pode ocorrer se os snapshots forem excluídos em um destino fora da recuperação de desastres do BlueXP . O serviço exclui o instantâneo na origem automaticamente a cada 24 horas. No entanto, você pode executar isso sob demanda. Esse recurso permite que você garanta que os snapshots sejam consistentes em todos os sites.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar planos de replicação"] consulte .



== 20 de setembro de 2024



=== Suporte para datastores VMware VMFS on-premises para locais

Esta versão inclui suporte para VMs montadas em armazenamentos de dados do sistema de arquivos de máquina virtual (VMFS) do VMware vSphere para iSCSI e FC protegidos para storage no local. Anteriormente, o serviço fornecia uma _visualização de tecnologia_ com suporte a armazenamentos de dados VMFS para iSCSI e FC.

Aqui estão algumas considerações adicionais sobre os protocolos iSCSI e FC:

* O suporte FC é para protocolos de front-end do cliente, não para replicação.
* A recuperação de desastres do BlueXP  oferece suporte a apenas um LUN por volume de ONTAP. O volume não deve ter vários LUNs.
* Para qualquer plano de replicação, o volume ONTAP de destino deve usar os mesmos protocolos que o volume ONTAP de origem que hospeda as VMs protegidas. Por exemplo, se a origem usar um protocolo FC, o destino também deve usar FC.




== 2 de agosto de 2024



=== Suporte para armazenamentos de dados VMware VMFS on-premises para FC

Esta versão inclui uma visualização de _tecnologia_ do suporte a VMs montadas nos armazenamentos de dados do sistema de arquivos de máquina virtual (VMFS) do VMware vSphere para FC protegido no storage local. Anteriormente, o serviço forneceu uma visualização de tecnologia com suporte aos datastores VMFS para iSCSI.


NOTE: A NetApp não cobra por nenhuma capacidade de workload visualizada.



=== Cancelar trabalho

Com esta versão, agora você pode cancelar um trabalho na IU do Monitor de trabalhos.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Monitorizar trabalhos"].



== 17 de julho de 2024



=== Programações de testes de failover

Esta versão inclui atualizações para a estrutura de agendamento de teste de failover, que era necessária para dar suporte a programações diárias e semanais. Esta atualização requer que você desative e reative todos os planos de replicação existentes para que você possa usar as novas programações de teste de failover diárias e semanais. Este é um requisito único.

Veja como:

. No menu superior, selecione *planos de replicação*.
. Selecione um plano e selecione o ícone ações para exibir o menu suspenso.
. Selecione *Desativar*.
. Após alguns minutos, selecione *Enable* (Ativar).




=== Atualizações do plano de replicação

Esta versão inclui atualizações para os dados do plano de replicação, que resolve um problema de "snapshot não encontrado". Isso exige que você altere a contagem de retenção em todos os planos de replicação para 1 e inicie um snapshot sob demanda. Esse processo cria um novo backup e remove todos os backups mais antigos.

Veja como:

. No menu superior, selecione *planos de replicação*.
. Selecione o plano de replicação, clique na guia *Mapeamento de failover* e clique no ícone de lápis *Editar*.
. Clique na seta *datastores* para expandi-la.
. Observe o valor da contagem de retenção no plano de replicação. Você precisará restaurar esse valor original quando terminar de executar estas etapas.
. Reduza a contagem para 1.
. Inicie um snapshot sob demanda. Para fazer isso, na página Plano de replicação, selecione o plano, clique no ícone ações e selecione *tirar instantâneo agora*.
. Depois que a tarefa de snapshot for concluída com êxito, aumente a contagem no plano de replicação de volta para o valor original que você anotou na primeira etapa.
. Repita estas etapas para todos os planos de replicação existentes.




== 5 de julho de 2024

Esta versão de recuperação de desastres do BlueXP  inclui as seguintes atualizações:



=== Suporte para AFF A-series

Esta versão suporta as plataformas de hardware da série A da NetApp AFF.



=== Suporte para datastores VMware VMFS on-premises para locais

Esta versão inclui uma visualização de _tecnologia_ do suporte para VMs montadas em datastores do sistema de arquivos de máquina virtual (VMFS) do VMware vSphere protegidos para armazenamento local. Com essa versão, a recuperação de desastres é suportada em uma prévia de tecnologia para cargas de trabalho VMware locais para ambientes VMware locais com datastores VMFS.


NOTE: A NetApp não cobra por nenhuma capacidade de workload visualizada.



=== Atualizações do plano de replicação

Você pode adicionar um plano de replicação mais facilmente filtrando as VMs por datastore na página aplicativos e selecionando mais detalhes de destino na página Mapeamento de recursos. Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].



=== Editar planos de replicação

Com esta versão, a página Mapeamentos de failover foi aprimorada para melhor clareza.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar planos"].



=== Editar VMs

Com esta versão, o processo de edição de VMs no plano incluiu algumas pequenas melhorias na interface do usuário.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar VMs"].



=== Atualizações de failover

Antes de iniciar um failover, agora você pode determinar o status das VMs e se elas estão ativadas ou desativadas. O processo de failover agora permite que você tire um snapshot agora ou escolha os snapshots.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover de aplicativos para um local remoto"].



=== Programações de testes de failover

Agora você pode editar os testes de failover e definir programações diárias, semanais e mensais para o teste de failover.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar planos"].



=== Atualizações para informações de pré-requisito

As informações dos pré-requisitos de recuperação de desastres do BlueXP  foram atualizadas.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Pré-requisitos de recuperação de desastres do BlueXP "].



== 15 de maio de 2024

Esta versão de recuperação de desastres do BlueXP  inclui as seguintes atualizações:



=== Replicação de workloads da VMware no local para no local

Este é agora lançado como um recurso de disponibilidade geral. Anteriormente, era uma visualização de tecnologia com funcionalidade limitada.



=== Atualizações de licenciamento

Com a recuperação de desastres do BlueXP , você pode se inscrever para uma avaliação gratuita de 90 dias, comprar uma assinatura PAYGO (pay-as-you-go) com o Amazon Marketplace ou trazer sua própria licença (BYOL), que é um arquivo de licença do NetApp (NLF) que você obtém de seu representante de vendas da NetApp ou do site de suporte da NetApp (NSS).

Para obter detalhes sobre como configurar o licenciamento para recuperação de desastres do BlueXP , link:../get-started/dr-licensing.html["Configure o licenciamento"]consulte .

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Saiba mais sobre a recuperação de desastres do BlueXP "].



== 5 de março de 2024

Esta é a versão de disponibilidade geral da recuperação de desastres do BlueXP , que inclui as seguintes atualizações.



=== Atualizações de licenciamento

Com a recuperação de desastres do BlueXP , você pode se inscrever para uma avaliação gratuita de 90 dias ou trazer sua própria licença (BYOL), que é um arquivo de licença do NetApp (NLF) que você obtém de seu representante de vendas da NetApp Você pode usar o número de série da licença para ativar o BYOL na carteira digital BlueXP . As cobranças de recuperação de desastres do BlueXP  são baseadas na capacidade provisionada dos armazenamentos de dados.

Para obter detalhes sobre como configurar o licenciamento para recuperação de desastres do BlueXP , https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configure o licenciamento"] consulte .

Para obter detalhes sobre como gerenciar licenças para serviços *All* BlueXP , https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Gerenciar licenças para todos os serviços BlueXP "^] consulte .



=== Editar programações

Com esta versão, agora você pode configurar programações para testar testes de conformidade e failover para garantir que eles funcionem corretamente caso você precise deles.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie o plano de replicação"] consulte .



== 1 de fevereiro de 2024

Esta versão de pré-visualização da recuperação de desastres do BlueXP  inclui as seguintes atualizações:



=== Melhoramento da rede

Com esta versão, agora você pode redimensionar os valores de CPU e RAM da VM. Agora você também pode selecionar um DHCP de rede ou endereço IP estático para a VM.

* DHCP: Se você escolher essa opção, você fornecerá credenciais para a VM.
* IP estático: Você pode selecionar as mesmas informações ou informações diferentes da VM de origem. Se você escolher o mesmo que a origem, não precisará inserir credenciais. Por outro lado, se você optar por usar informações diferentes da origem, poderá fornecer as credenciais, o endereço IP, a máscara de sub-rede, o DNS e as informações do gateway.


Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Scripts personalizados

Agora pode ser incluído como processos de pós-failover. Com scripts personalizados, você pode fazer com que a recuperação de desastres do BlueXP  execute seu script após um processo de failover. Por exemplo, você pode usar um script personalizado para retomar todas as transações de banco de dados após a conclusão do failover.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover para um local remoto"] consulte .



=== Relação de SnapMirror

Agora você pode criar uma relação do SnapMirror enquanto desenvolve o plano de replicação. Anteriormente, você tinha que criar o relacionamento fora da recuperação de desastres do BlueXP .

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Grupos de consistência

Ao criar um plano de replicação, você pode incluir VMs de diferentes volumes e SVMs diferentes. A recuperação de desastres do BlueXP  cria uma consistência do Snapshot do grupo, incluindo todos os volumes e atualizações de todos os locais secundários.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Opção de atraso de ativação da VM

Ao criar um plano de replicação, você pode adicionar VMs a um grupo de recursos. Com grupos de recursos, você pode definir um atraso em cada VM para que eles ativem uma sequência atrasada.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



=== Cópias Snapshot consistentes com aplicações

Você pode especificar para criar cópias Snapshot consistentes com a aplicação. O serviço desativará o aplicativo e, em seguida, fará uma captura Instantânea para obter um estado consistente do aplicativo.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"] consulte .



== 11 de janeiro de 2024

Esta versão de pré-visualização da recuperação de desastres do BlueXP  inclui as seguintes atualizações:



=== Dashboard mais rápido

Com esta versão, você pode acessar informações sobre outras páginas a partir do Dashboard mais rapidamente.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Saiba mais sobre a recuperação de desastres do BlueXP "].



== 20 de outubro de 2023

Esta versão de pré-visualização da recuperação de desastres do BlueXP  inclui as seguintes atualizações.



=== Proteja workloads da VMware baseados em NFS no local

Agora, com a recuperação de desastres da BlueXP , você pode proteger workloads da VMware baseados em NFS no local contra desastres em outro ambiente VMware on-premises e baseado em NFS, além da nuvem pública. A recuperação de desastres do BlueXP  orquestra a conclusão dos planos de recuperação de desastre.


NOTE: Com esta oferta de pré-visualização, a NetApp reserva-se o direito de modificar os detalhes da oferta, o conteúdo e o cronograma antes da disponibilidade geral.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Saiba mais sobre a recuperação de desastres do BlueXP "].



== 27 de setembro de 2023

Esta versão de pré-visualização da recuperação de desastres do BlueXP  inclui as seguintes atualizações:



=== Atualizações do painel

Agora você pode clicar nas opções no Painel, facilitando a revisão das informações rapidamente. Além disso, o Dashboard agora mostra o status de failovers e migrações.

Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Veja a integridade dos seus planos de recuperação de desastres no Dashboard"].



=== Atualizações do plano de replicação

* *RPO*: Agora você pode inserir o objetivo do ponto de recuperação (RPO) e a contagem de retenção na seção datastores do plano de replicação. Isso indica a quantidade de dados que devem existir que não é mais antiga do que a hora definida. Se, por exemplo, você os definir em 5 minutos, o sistema poderá perder até 5 minutos de dados em caso de desastre sem impactar as necessidades essenciais aos negócios.
+
Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].

* *Melhorias de rede*: Quando você está mapeando redes entre locais de origem e destino na seção máquinas virtuais do plano de replicação, a recuperação de desastres do BlueXP  agora oferece duas opções: DHCP ou IP estático. Anteriormente, apenas DHCP era suportado. Para IPs estáticos, você configura os servidores de sub-rede, gateway e DNS. Além disso, agora você pode inserir credenciais para máquinas virtuais.
+
Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].

* *Editar horários*: Agora você pode atualizar os planos de replicação.
+
Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gerenciar recursos"].

* *SnapMirror Automation*: Enquanto estiver criando o plano de replicação nesta versão, você pode definir a relação SnapMirror entre os volumes de origem e destino em uma das seguintes configurações:
+
** 1 a 1
** 1 para muitos em uma arquitetura de fanout
** Muitos a 1 como um Grupo de consistência
** Muitos a muitos
+
Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].







== 1 de agosto de 2023



=== Prévia da recuperação de desastres do BlueXP 

A prévia da recuperação de desastres do BlueXP  é um serviço de recuperação de desastres baseado na nuvem que automatiza os workflows de recuperação de desastres. Inicialmente, com a prévia da recuperação de desastres do BlueXP , você pode proteger seus workloads da VMware baseados em NFS no local que executam o armazenamento do NetApp para o VMware Cloud (VMC) na AWS com o Amazon FSX for ONTAP.


NOTE: Com esta oferta de pré-visualização, a NetApp reserva-se o direito de modificar os detalhes da oferta, o conteúdo e o cronograma antes da disponibilidade geral.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Saiba mais sobre a recuperação de desastres do BlueXP "].

Esta versão inclui as seguintes atualizações:



=== Atualização dos grupos de recursos para a ordem de inicialização

Ao criar um plano de recuperação de desastres ou replicação, você pode adicionar máquinas virtuais a grupos de recursos funcionais. Os grupos de recursos permitem que você coloque um conjunto de máquinas virtuais dependentes em grupos lógicos que atendam aos seus requisitos. Por exemplo, grupos podem conter ordem de inicialização que pode ser executada após a recuperação. Com esta versão, cada grupo de recursos pode incluir uma ou mais máquinas virtuais. As máquinas virtuais serão ligadas com base na sequência em que as incluir no plano. Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Selecione aplicativos para replicar e atribuir grupos de recursos"].



=== Verificação de replicação

Depois de criar o plano de recuperação de desastre ou replicação, identifique a recorrência no assistente e inicie uma replicação para um local de recuperação de desastres, a cada 30 minutos a recuperação de desastres do BlueXP  verifica se a replicação está realmente ocorrendo de acordo com o plano. Pode monitorizar o progresso na página Monitor de trabalhos.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Replique aplicações para outro local"]Consulte a .



=== O plano de replicação mostra os cronogramas de transferência do objetivo do ponto de restauração (RPO)

Ao criar um plano de recuperação de desastres ou replicação, você seleciona as VMs. Nesta versão, agora é possível exibir o SnapMirror associado a cada um dos volumes associados ao datastore ou à VM. Você também pode ver as programações de transferência RPO associadas ao cronograma do SnapMirror. O RPO ajuda a determinar se a programação do backup é suficiente para se recuperar após um desastre. Consulte a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].



=== Atualização do Monitor de trabalho

A página Monitor de trabalhos agora inclui uma opção Atualizar para que você possa obter um status atualizado das operações.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Monitorar trabalhos de recuperação de desastres"]Consulte a .



== 18 de maio de 2023

Este é o lançamento inicial da recuperação de desastres do BlueXP .



=== Serviço de recuperação de desastres baseado na nuvem

O BlueXP  Disaster Recovery é um serviço de recuperação de desastres baseado na nuvem que automatiza os workflows de recuperação de desastres. Inicialmente, com a prévia da recuperação de desastres do BlueXP , você pode proteger seus workloads da VMware baseados em NFS no local que executam o armazenamento do NetApp para o VMware Cloud (VMC) na AWS com o Amazon FSX for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Saiba mais sobre a recuperação de desastres do BlueXP "].
